import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "./index.module.scss"
import cx from "classnames"
import seo from "../public/images/slider-dec.png"
import ContactForm from "../components/index/ContactForm"
import RightDec from "/public/images/slider-right-dec.svg"
import SeoIsometric from "/public/images/seo-isometric.svg"
import DeveloperIsometric from "/public/images/web-developer-isometric.svg"
import EasterEggsIsometric from "/public/images/easter-eggs-isometric.svg"
import CardPaymentIsometric from "/public/images/card-payment-isometric.svg"
import Settings from "/public/icons/settings.svg"
import Advantage from "../components/index/Advantage"
import Feature from "../components/index/Feature"
import Section from "../components/common/Section"
import Title from "../components/common/Title"

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={"banner"}>
          <div className={cx(styles.container, "container")}>
            <div className={styles.fr1}>
              <h2 className={styles.brand}>Digital Media Agency</h2>
              <h1>精通SEO的網頁設計公司</h1>
              <p>
                不同於傳統的設計公司，＿＿具有獨立的工程部門負責搜尋引擎優化、自適應網頁開發、持續整合與應用程式狀態監控。我們用開發企業級網頁應用程式的規格，完成客戶的每一個專案。
              </p>
              <a href="#contact" className={cx("button", "outlined")}>
                免費諮詢
              </a>
            </div>
            <div className={cx(styles.fr1, styles.dec)}>
              <Image src={seo} alt="SEO" />
              <RightDec className={styles.decBg} />
            </div>
          </div>
        </section>

        <Section
          className={cx(styles.about)}
          containerClassName={styles.container}
        >
          <div className={styles.fr1}>
            <Image src={seo} alt="SEO" />
          </div>
          <div className={styles.fr1}>
            <h3 className={"subtitle"}>服務項目</h3>
            <h2 className={"title"}>我們能幫你做到什麼</h2>
            <div className={"line"}></div>
            <p>
              從網站規劃到正式上線與後續維護... 網頁視覺畫面設計 關鍵字廣告投放
              套版 客製 自適應網頁設計(RWD) 搜尋引擎優化(SEO)
            </p>
          </div>
        </Section>

        <Section className={cx(styles.advantages)}>
          <Title subtitle="Our Services" title="為什麼選擇。。" />
          <div className={cx(styles.advantageContainer)}>
            <Advantage
              title="我們SEO很厲害"
              content="We hope this DigiMedia template is useful for your work. You
                  can use this template for any purpose. You may contribute a
                  little amount via"
              picture={<SeoIsometric />}
            />
            <Advantage
              title="我們技術很厲害"
              content="We hope this DigiMedia template is useful for your work. You
                  can use this template for any purpose. You may contribute a
                  little amount via"
              picture={
                <DeveloperIsometric style={{ transform: "scaleX(-1)" }} />
              }
            />
            <Advantage
              title="我們有可愛小雞"
              content="We hope this DigiMedia template is useful for your work. You
                  can use this template for any purpose. You may contribute a
                  little amount via"
              picture={<EasterEggsIsometric />}
            />
            <Advantage
              title="我們削價競爭"
              content="We hope this DigiMedia template is useful for your work. You
                  can use this template for any purpose. You may contribute a
                  little amount via"
              picture={<CardPaymentIsometric />}
            />
          </div>
        </Section>

        <Section className={cx(styles.features)}>
          <Title subtitle="Our Services" title="我們的服務" />
          <div className={styles.featuresContainer}>
            {new Array(6).fill("").map((x, i) => (
              <Feature
                key={i}
                title="123"
                content="We hope this DigiMedia template is useful for your work. You
                  can use this template for any purpose. You may contribute a
                  little amount via"
                icon={<Settings />}
              />
            ))}
          </div>
        </Section>

        <Section
          id="contact"
          className={cx(styles.contact)}
          containerClassName={styles.contactContainer}
        >
          <div className={styles.fr1}>
            <Title
              subtitle="聯絡我們"
              title="Who is DigiMedia Agency"
              align="left"
            />
            <p className={cx(styles.description)}>
              We hope this DigiMedia template is useful for your work. You can
              use this template for any purpose. You may contribute a little
              amount via PayPal to support TemplateMo in creating new templates
              regularly.
            </p>
          </div>
          <div className={styles.fr1}>
            <ContactForm />
          </div>
        </Section>
      </main>
    </>
  )
}

export default Index
