import type { NextPage } from "next"
import Head from "next/head"
import styles from "./index.module.scss"
import cx from "classnames"

const Test: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="banner">Test Page</section>
      </main>
    </>
  )
}

export default Test
